# Generated by Django 3.2.9 on 2021-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0007_auto_20211213_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='is employee'),
        ),
    ]
