# Generated by Django 3.2.9 on 2021-12-13 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_baseuser_is_employee"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="baseuser",
            managers=[],
        ),
    ]
