# Generated by Django 3.2.9 on 2022-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0011_auto_20220102_2300"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="detail",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Описание"
            ),
        ),
    ]
